blog/urls.py
from django.urls import path
from . import views
from .feeds import LatestPostsFeed

app_name = 'blog'

urlpatterns= [
    #post views

    path('',views.post_list, name='post_list'),
    # path('', views.PostListView.as_view(), name ='post_list'),
    path('tag/<slug:tag_slug>/', views.post_list, name = 'post_list_by_tag'),
    path('<int:year>/<int:month>/<int:day>/<slug:post>',
                                    views.post_detail,
                                    name='post_detail'),

    path('<int:post_id>/share/', views.post_share, name  = 'post_share'),
    path('feed/', LatestPostsFeed(), name = 'post_feed'),
    path('search/', views.post_search, name = 'post_search'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.sitemaps.views import sitemap
from blog.sitemaps import PostSitemap

sitemaps = {
    'posts': PostSitemap,
}


urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/',include('blog.urls', namespace = 'blog')),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps},
        name = 'django.contrib.sitemaps.views.sitemap')
]

blog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse
from taggit.managers import TaggableManager

# Create your models here.

class PublishedManager(models.Manager):
        def get_queryset(self):
            return super(PublishedManager, self).get_queryset()\
                .filter(status='published')
    


class Post (models.Model):
    STATUS_CHOICES = (
        ('draft', 'Draft'),
        ('published', 'Published'),
    )
    title = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250, unique_for_date = 'publish')
    author = models.ForeignKey(User,on_delete=models.CASCADE, related_name = 'blog_posts')
    body = models.TextField()

    publish = models.DateTimeField(default = timezone.now)
    created = models.DateTimeField(auto_now_add = True)
    updated = models.DateTimeField(auto_now = True)
    status = models.CharField(max_length = 10, choices=STATUS_CHOICES, default = 'draft')

    class Meta:
        ordering = ('-publish',)

    def __str__(self):
        return self.title

    objects = models.Manager()
    published = PublishedManager()
    tags = TaggableManager()
    
    def get_absolute_url(self):
        return reverse('blog:post_detail',
                        args = [self.publish.year,
                                self.publish.month,
                                self.publish.day,
                                self.slug])


class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE,
                                    related_name='comments')
    name = models.CharField(max_length  = 80)
    email = models.EmailField()
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)
    
    class Meta:
        ordering = ('created',)

    def __str__(self):
        return f'Commented by  {self.name}  on {self.post}'

blog/forms.py
from django import forms
#
from .models import Comment

class EmailPostForm(forms.Form):
    name = forms.CharField(max_length =25)
    email = forms.EmailField()
    to = forms.EmailField()
    comments = forms.CharField(required=False, widget = forms.Textarea)

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields  = ('name', 'email','body')

class SearchForm(forms.Form):
    query = forms.CharField()
    

blog/views.py
from django.shortcuts import render, get_object_or_404
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.views.generic import ListView
from django.core.mail import send_mail
from taggit.models import Tag
from django.db.models import Count
from django.contrib.postgres.search import SearchVector, SearchQuery, SearchRank, TrigramSimilarity


# Create your views here.
from .models import Post, Comment
from .forms import EmailPostForm , CommentForm, SearchForm

# class PostListView(ListView):
#     queryset = Post.published.all()
#     context_object_name = 'posts'
#     paginate_by = 5
#     template_name = 'blog/post/list.html'



def post_detail (request, year, month, day, post):
    post = get_object_or_404(Post, 
                                slug=post,
                                status = 'published',
                                publish__year = year,
                                publish__month = month,
                                publish__day = day)

    # List of active comments for this post
    comments = post.comments.filter(active=True)

    new_comment = None

    if request.method == 'POST':
        #A comment  was posted
        comment_form = CommentForm(data = request.POST)
        if comment_form.is_valid():
            #Create comment objectt but dont save to database
            new_comment = comment_form.save(commit=False)
            #assign the current post to comment
            new_comment.post = post
            # save the comment to the database
            new_comment.save()
    else:
        comment_form = CommentForm()

    # List of similar posts
    post_tags_ids = Post.tags.values_list('id', flat=True)
    similar_posts = Post.published.filter(tags__in=post_tags_ids)\
                                                .exclude(id=post.id)
    similar_posts = similar_posts.annotate(same_tags=Count('tags'))\
                                        .order_by('-same_tags', '-publish')[:4]


    return  render(request,'blog/post/detail.html', {'post':post,
                                                    'comments':comments,
                                                    'new_comment':new_comment,
                                                    'comment_form':comment_form,
                                                    'similar_posts': similar_posts})







def post_share(request, post_id):
    #retrive post by id
    post  = get_object_or_404(Post, id = post_id, status='published')
    sent = False
    if request.method == 'POST':
        #form was submitted
        form = EmailPostForm(request.POST)
        if form.is_valid():
            # Forrm Fields passed validation
            cd = form.cleaned_data
            # ...send email
            post_url = request.build_absolute_uri(post.get_absolute_url())
            
            subject = f"{cd['name']} recommends you read " \
                         f"{post.title}"

            message = f"Read {post.title} at {post_url}\n\n" \
                         f"{cd['name']}\'s comments: {cd['comments']}"
            send_mail(subject, message, 'admin@myblog.com',[cd['to']])
            sent = True


    else:
        form = EmailPostForm()
    return render(request, 'blog/post/share.html', {'post':post, 'form':form, 'sent':sent})






def post_list(request, tag_slug = None):
    
    posts = Post.published.all()
    
    object_list = Post.published.all()

    tag = None
    if tag_slug:
        tag = get_object_or_404(Tag, slug = tag_slug)
        object_list = object_list.filter(tags__in=[tag])


    paginator = Paginator(object_list, 3) # 3 posts in each page
    page = request.GET.get('page')
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer delivery the first page
        posts = paginator.page(1)
    except EmptyPage:
        #  If pagee is out of range deliver last page of results
        posts = paginator.page(paginator.num_pages)

    return render(request,
                     'blog/post/list.html',
                    {'page': page,
                     'posts': posts,
                     'tag': tag})

def post_search(request):
    form = SearchForm()
    query = None
    results = []

    if 'query' in request.GET:
        form = SearchForm(request.GET)
        if form.is_valid():
            query = form.cleaned_data['query']
            
            search_vector = SearchVector('title', weight='A') + SearchVector('body', weight='B')
            search_query = SearchQuery(query)
            
            results = Post.published.annotate(
                    search = search_vector,
                    rank = SearchRank(search_vector, search_query)
                    ).filter(rank__gte=0.3).order_by('-rank')
                    
            # results = Post.published.annotate(
            #     similarity = TrigramSimilarity('title', query),
            # ).filter(similarity__gt=0.1).order_by('-similarity')


    return render(request, 'blog/post/search.html',
                                {'form': form,
                                 'query': query,
                                 'results': results})

blog/templates/blog/base.html
{% load blog_tags %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{% static '/bootstrap/css/bootstrap.css' %}">
    <!-- #####  -->
  
</head>

<body class="container" style="background-color: rgb(55, 31, 113);" >

    <div class="my-3 p-3 bg-white rounded shadow-sm">
    <a href="{% url 'blog:post_list' %}">
        <div style="margin: 10px;"><h3>My Blog</h3></div>
    </a>
    <p>
        <a href="{% url 'blog:post_feed' %}">Subscribe to my RSS feed</a>
    </p>
    
</div>
    

   
    <div id='content'>
        {% block content %}
        {% endblock %}
    </div>
    <div class="my-3 p-3 bg-white rounded shadow-sm">
        <h3>Latest posts</h3>
        {% show_latest_posts %}

        <h3>Most Commented Posts</h3>
        {% get_most_commented_posts as most_commented_posts %}
        <ul>
            {% for post in most_commented_posts %}
            <li>
                <a href="{{ post.get_absolute_url }}">
                    {{ post.title }}
                </a>
            </li>
            {% endfor %}
          
            
        </ul>
       
    </div>







</body>





</html>

blog/templates/blog/post/detail.html
{% extends 'blog/base.html' %}
{% load crispy_forms_tags %}
{% load blog_tags %}

{% block title %} {{ post.title }} {% endblock %}



{% block content %}



    <div class="my-3 p-3 bg-white rounded shadow-sm">
        <h4 class="border-bottom border-gray pb-2 mb-0">{{ post.title }}</h4>
        <div>{{ post.body|markdown }}</div>
        <div class="media text-muted pt-3">
          <!-- <svg class="bd-placeholder-img mr-2 rounded" width="32" height="32" xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMidYMid slice" focusable="false" role="img" aria-label="Placeholder: 32x32"><title>Placeholder</title><rect width="100%" height="100%" fill="#007bff"/><text x="50%" y="50%" fill="#007bff" dy=".3em">32x32</text></svg> -->
          <div class="media-body pb-3 mb-0 small lh-125 border-bottom border-gray">
            
            <div class="d-flex justify-content-between align-items-center w-100">
              <a href="{% url 'blog:post_share' post.id %}">Share this post</a>
            </div>
            <span class="d-block">published {{ post.publish }} by {{ post.author }}</span>
          </div>
        </div>
    </div>







    
    <div class="my-3 p-3 bg-white rounded shadow-sm">

      <h6 class="border-bottom border-gray pb-2 mb-0">Similar Posts</h6>

        {% for post in similar_posts %}
        <p>
          <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
        </p>
        {% empty %}
        There are no similar posts yet.
        {% endfor %}


        <h6 class="border-bottom border-gray pb-2 mb-0">Recent updates</h6>


        {% with comments.count as total_comments %}
        <h2>
            {{ total_comments }} comment{{ total_comments|pluralize }}
        </h2>
        {% endwith %}


        
    <!-- <div class="comment">
        <p class="info">
            Comment {{ forloop.counter }} by {{ comment.name }}
            {{comment.create}}
        </p>
        <div>{{ comment.body|linebreaks }}</div> -->
        
        

        {% for comment in comments %}
        <div class="media text-muted pt-3">
          <svg class="bd-placeholder-img mr-2 rounded" width="32" height="32" xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMidYMid slice" focusable="false" role="img" aria-label="Placeholder: 32x32"><title>Placeholder</title><rect width="100%" height="100%" fill="#007bff"/><text x="50%" y="50%" fill="#007bff" dy=".3em">32x32</text></svg>
          <p class="media-body pb-3 mb-0 small lh-125 border-bottom border-gray">
            <strong class="d-block text-gray-dark">{{ comment.name }}{{comment.create}}</strong>
            {{ comment.body }}
          </p>
        </div>
        
        {% empty %}
        <p>There are no comments yet.</p>
        {% endfor %}


    <div style="margin: 20px;">
        {% if new_comment %}
        <h2>your comment has been added</h2>
        {% else %}
        <form action="" method="POST" class="uniForm">
            {{ comment_form|crispy }}
            {% csrf_token %}
            <p>
            <input class="btn btn-primary" type="submit" value="Add comment"></p>
        </form>
        {% endif %}
    </div>

{% endblock %}

blog/templates/blog/post/latest_posts.html
<div >
<ul>
    {% for post in latest_posts %}
    <li>
        <a href="{{ post.get_absolute_url }}">
            {{ post.title }}
        </a>
    </li>
    {% endfor %}
</ul>
</div>

blog/templates/blog/post/list.html
{% extends 'blog/base.html' %}
{% load blog_tags %}

{% block title %} My Blog {% endblock %}

{% block content %}
    {% for post in posts %}

    <div class="row mb-2">
        <div class="col-md-6">
          <div class="row no-gutters border bg-white rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 position-relative">
            <div class="col p-4 d-flex flex-column position-static">
              <strong class="d-inline-block mb-2 text-primary">{{ post.author }}</strong>
              <h3 class="mb-0"><a href="{{ post.get_absolute_url }}">
                {{ post.title }}
                </a></h3>


                <p class="tags">
                {% for tag in post.tags.all %}
                <a href="{% url 'blog:post_list_by_tag' tag.slug %}">
                  {{ tag.name }}
                </a>
                {% if not forloop.last %}, {% endif %}
                {% endfor %}
                </p>


              <div class="mb-1 text-muted">Published {{ post.publish }}</div>
              <p class="card-text mb-auto">{{ post.body|markdown|truncatewords:30 }}</p>
              <a href="{{ post.get_absolute_url }}">Continue reading</a>
            </div>
            <!-- <div class="col-auto d-none d-lg-block">
              <svg class="bd-placeholder-img" width="200" height="250" xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMidYMid slice" focusable="false" role="img" aria-label="Placeholder: Thumbnail"><title>Placeholder</title><rect width="100%" height="100%" fill="#55595c"/><text x="50%" y="50%" fill="#eceeef" dy=".3em">Thumbnail</text></svg>
            </div> -->
          </div>
        </div>
      </div>
    </div>
    {% endfor %}



    <div class="my-1 p-1 bg-white rounded shadow-sm">
    {% include "pagination.html" with page=posts %}

    {% if tag %}
    <h2>Posts tagged with "{{ tag.name }}"</h2>
    {% endif %}


    <div class="mb-1 text-muted">Currently {% total_posts %} Posts on this blog</div>
    
    </div>
{% endblock %}

blog/templates/blog/post/search.html
{% extends 'blog/base.html' %}
{% load blog_tags %}

{% load crispy_forms_tags %}

{% block title %}Search{% endblock %}

{% block content %}
<div class="my-1 p-1 bg-white rounded shadow-sm">
{% if query %}

    <h1>Posts containing {{ query }}</h1>
    <h3>
        {% with results.count as total_results %}
        Found {{ total_results }} result{{ total_results|pluralize }}
        {% endwith %}
    </h3>
    {% for post in results %}
    <h4><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></h4>
    {{ post.body|markdown|truncatewords_html:5 }}
    {% empty %}
    <div class="mb-1 text-muted"><p>There are no results for your query...</p></div>
    {% endfor %}

    <p><a href="{% url 'blog:post_search' %}">Search again</a></p>
{% else %}
<h1>Search for posts</h1>
<form method="GET">
    {{ form|crispy }}
    <input type="submit" value="search">
</form>

{% endif %}
</div>
{% endblock %}

blog/templates/blog/post/share.html
{% extends 'blog/base.html' %}
{% load crispy_forms_tags %}


{% block title %} Share a Post {% endblock title %}

{% block content %}
<div class="my-3 p-3 bg-white rounded shadow-sm">
{% if sent %}
<h1>Email successfully sent</h1>
<p>
'{{post.title}}' was succcessfully sent to {{ form.cleaned_data.to }}.
</p>
{% else %}

<h1>Share {{ post.title }} by  Email</h1>

<form action="" method="POST" >
    {% csrf_token %}
    {{ form|crispy }}
    <input type="submit" value="Send Email">
</form>
{% endif %}
</div>
{% endblock content %}

blog/templates/pagination.html
<div class="pagination">
    <h3>
    <span class="step-links">
      {% if page.has_previous %}
        <a href="?page={{ page.previous_page_number }}">Previous</a>
      {% endif %}
      <span class="current">
        Page {{ page.number }} of {{ page.paginator.num_pages }}.
      </span>
      {% if page.has_next %}
        <a href="?page={{ page.next_page_number }}">Next</a>
      {% endif %}
    </span>
    </h3>
</div>